In [44]:
import numpy as np

# ones_like: Retruns an array of ones with shape & type of input.
#ones array returns an array with ones.
#zeroes_like: Returns an erray of zeros with shape & type of input.
#zeroes array returns an array with zeroes.
#empty_like: Returns an empty array with shape & type of input.
#full_like: returns a new array with shape of input filled with value.


#ones array

In [63]:
a=np.ones(2)

In [64]:
print(a)

[1. 1.]


In [4]:
a2=np.ones([2,2])

In [5]:
print(a2)

[[1. 1.]
 [1. 1.]]


In [6]:
a3=np.ones([2,3])

In [7]:
print(a3)

[[1. 1. 1.]
 [1. 1. 1.]]


#ones_like

In [8]:
b=np.arange(6).reshape(2,3)

In [9]:
print(b)

[[0 1 2]
 [3 4 5]]


In [10]:
b1=np.ones_like(b)

In [11]:
print(b1)

[[1 1 1]
 [1 1 1]]


In [12]:
#ones_like only takess in a array. It converts the array to ones array.

#zeros

In [13]:
c=np.zeros(2)

In [14]:
print(c)

[0. 0.]


In [15]:
c1=np.zeros([2,3])

In [16]:
print(c1)

[[0. 0. 0.]
 [0. 0. 0.]]


#zeros_like

In [17]:
d=np.arange(8).reshape(2,4)

In [18]:
print(d)

[[0 1 2 3]
 [4 5 6 7]]


In [19]:
d1=np.zeros_like(d)

In [20]:
print(d1)

[[0 0 0 0]
 [0 0 0 0]]


In [21]:
#zeros_like only takes in a array. It converts the array to zeros array.

#full 

In [22]:
e=np.full([6],50)

In [23]:
print(e)

[50 50 50 50 50 50]


In [24]:
e1=np.full([2,3],25)

In [25]:
print(e1)

[[25 25 25]
 [25 25 25]]


In [26]:
#full will take an arugemnt which will fill the array withat argument number provided.

In [27]:
e2=np.arange(9).reshape(3,3)

In [28]:
print(e2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
e3=np.full_like(e2,100)

In [30]:
print(e3)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


#empty

In [31]:
f=np.empty([3,3])

In [32]:
print(f)

[[1.49166815e-154 1.49166815e-154 3.45845952e-323]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [33]:
#empty o/p is negligible 0s.

In [34]:
f2=np.arange(12).reshape(2,6)

In [35]:
print(f2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [36]:
f3=np.empty_like(f2)

In [37]:
print(f3)

[[2305843009213693952 2305843009213693952 2305843009213693958
  2305843009213693952                   5 4189022123868430971]
 [2482738415875158818 4189038663854989868 3833161645695916834
  6566369599685997088 3833161645692040498    1826436694170973]]


In [38]:
#empty_like will have same value as the original array which is used to pass.

#eye function returns a 2d array with 1s on the diagonal.In eye function ur passing the arguments but not the array
#the parmater must be in a n int form.

In [58]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [59]:
print(np.eye(1,3))

[[1. 0. 0.]]


In [60]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [61]:
#np.eye([2]) #error 

In [62]:
#np.eye([2,3]) type error list object cant be inteperted as int.

TypeError: 'list' object cannot be interpreted as an integer

In [65]:
#identity matrix. Its a square array with 1s on the diagonal

In [66]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [70]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
#identity takes in only 1 int argument.

In [72]:
#diagonals. k>0 upper diagonals. & k<0 lower diagonals.

In [74]:
x=np.arange(9).reshape(3,3)

In [75]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [76]:
np.diag(x)

array([0, 4, 8])

In [77]:
np.diag(x,k=1)

array([1, 5])

In [78]:
np.diag(x,k=2)

array([2])

In [79]:
np.diag(x,k=3)

array([], dtype=int64)

In [80]:
np.diag(x,k=-1)

array([3, 7])