In [1]:
import numpy as np

In [2]:
arr=np.arange(15).reshape(5,3)

In [3]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [4]:
arr.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

 #transpose converts rows into columns.

In [5]:
arr1=np.arange(16).reshape(2,2,4) #(sets,rows,columns are in [0,1,2]. Based on this the transpose will work.)


In [ ]:
#the above array arr1 will have 2 sets,2 rows & 4columns.

In [6]:
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [9]:
arr1.transpose(2,0,1) 

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

#(2,0,1) will be compared to (0,1,2) in orginal array.
#As 2 is first in the transpose it takes in value of 2 in orignal array which is 4 
and configures the sets to 4 in transpose array.
Similarly is the case with rows & columns.

In [10]:
arr1.transpose(1,2,0)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [11]:
#(2,2,4) is set as (0,1,2) will changed accordingly in transpose values. in (2,0,1) its changed as (4,2,2)
#in (1,2,0) its changes as (2,4,2)

In [12]:
a1=np.arange(10)

In [13]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.log(a1)

/Users/saisandeeptatineni/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.exp(a1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
np.max(a1)

9

In [18]:
np.min(a1)

0

In [20]:
x=np.random.rand(8).reshape(2,4)
y=np.array([[1,2,3,4],[5,6,7,8]])


In [21]:
print(x)
print(y)

[[0.18535749 0.54374357 0.71497695 0.22755081]
 [0.48749719 0.18299609 0.34268197 0.75431671]]
[[1 2 3 4]
 [5 6 7 8]]


In [22]:
np.maximum(x,y)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [23]:
np.minimum(x,y)

array([[0.18535749, 0.54374357, 0.71497695, 0.22755081],
       [0.48749719, 0.18299609, 0.34268197, 0.75431671]])

In [30]:
ary=np.random.randn(7)

In [31]:
print(ary)

[-0.71342012 -0.10566515 -1.95321441  0.20537259  0.21543551  0.16037676
  0.69852581]


In [32]:
ary*5

array([-3.56710059, -0.52832575, -9.76607206,  1.02686296,  1.07717753,
        0.80188382,  3.49262903])

In [33]:
a,b=np.modf(ary)

In [34]:
a

array([-0.71342012, -0.10566515, -0.95321441,  0.20537259,  0.21543551,
        0.16037676,  0.69852581])

In [35]:
b

array([-0., -0., -1.,  0.,  0.,  0.,  0.])

In [36]:
#sum,cumlative sum

In [37]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
z.sum()

45

In [40]:
z.prod()

362880

In [41]:
z.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [42]:
z.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [43]:
z.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [44]:
z.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [45]:
z.mean()

5.0

In [47]:
z.var()

6.666666666666667

In [48]:
#variance=summation(x-x**2)/n-1

In [49]:
z.std()

2.581988897471611

In [ ]:
 #std is sqrt(var)