In [1]:
import numpy as np

In [33]:
a=np.array([1,2,3])

In [34]:
a

array([1, 2, 3])

In [35]:
print(a)

[1 2 3]


In [7]:
b=np.array([1.,2,3]) # If you have diffent data types in a array all the items are converted into same datatype.

In [8]:
print(b)

[1. 2. 3.]


In [9]:
c=np.array((1,2,3))

In [10]:
print(c)

[1 2 3]


In [12]:
d=np.array({1,2,3})

In [13]:
print(d)

{1, 2, 3}


In [14]:
# in arrays exclude the concept of lists,sets & tuples all are arrays.

#2d arrays

In [21]:
a2=np.array([[1,2,3],[4,5,6]])

In [17]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [18]:
a2b=np.array([(1,2,3),(4,5,6)])

In [19]:
print(a2b)

[[1 2 3]
 [4 5 6]]


In [22]:
#make sure the arrays are close with enclosing[]

In [23]:
a2.ndim

2

# '''axis 0 are rows & axis 1 are columns. 
-------->
| (axis 1) columns
|
|
|
|
|
|(axis 0) rows
^

'''

In [41]:
a2m=np.array([[1,2,3],[4,5,6]])

In [42]:
print(a2m)

[[1 2 3]
 [4 5 6]]


In [43]:
a2m.ndim

2

In [44]:
a2m.size

6

In [45]:
a2m.itemsize

8

In [46]:
a2m.shape

(2, 3)

In [54]:
a2m.dtype

dtype('int64')

# float 2d array

In [47]:
a2f=np.array([[1.,2,3],[4,5,6]])

In [48]:
print(a2f)

[[1. 2. 3.]
 [4. 5. 6.]]


In [50]:
a2f.ndim

2

In [51]:
a2f.shape

(2, 3)

In [52]:
a2f.size

6

In [53]:
a2f.itemsize

8

In [55]:
a2f.dtype

dtype('float64')

# 2d array string

In [56]:
a2s=np.array([[1.,'hELLO',3],[4,5,6]])

In [57]:
print(a2s)

[['1.0' 'hELLO' '3']
 ['4' '5' '6']]


In [58]:
a2s.ndim

2

In [59]:
a2s.shape

(2, 3)

In [60]:
a2s.size

6

In [61]:
a2s.itemsize

128

In [108]:
a2s1=np.array(['1','3o','hell0'])

In [109]:
print(a2s1)

['1' '3o' 'hell0']


In [110]:
a2s1.size

3

In [111]:
a2s1.itemsize

20

### Advantage of Numpy over List
Less Memory
Fast & Convinient

In [112]:
#Memory comparision

In [113]:
import time
import sys

In [114]:
s=range(1000)
print(sys.getsizeof(10)*len(s))


28000


#calculating the the memory occupied by single element in range with its length gives total memory occupied

In [115]:
D=np.arange(1000)

In [121]:
print(D.size*D.itemsize)

8000


In [117]:
D.ndim

1

In [119]:
D.shape

(1000,)

In [122]:
D.size

1000

In [123]:
D.itemsize

8

In [124]:
print(D)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#faster computation

In [131]:
size=1000000
l1=range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)


In [132]:
start=time.time()
result=[(x,y) for x,y in zip(l1,l2)]
print(time.time()-start)

0.3227241039276123


In [133]:
start=time.time()
result=a1+a2
print(time.time()-start)

0.08155202865600586


#you can add arrays directly.
#The time for list range is like 0.32 sec approx. Fot arrays its 0.08sec approx.
#Hence Numpy is faster than lists.

In [134]:
print(l1)

range(0, 1000000)
