In [1]:
import numpy as np

In [2]:
a=np.array([[11,2,3],[5,4,8]])

In [3]:
a.sort(axis=1)

In [4]:
print(a)

[[ 2  3 11]
 [ 4  5  8]]


In [5]:
a.sort(axis=0)

In [6]:
print(a)

[[ 2  3  8]
 [ 4  5 11]]


#sort will sort the order of array & stays as it is.
axis=0 will sort according to row & axis=1 will sort according to columns.

In [7]:
arr=np.random.randn(10)

In [8]:
arr

array([-0.40217787, -0.52484577, -1.61600169, -0.87328739,  0.45613827,
        0.37318812, -0.38252724,  0.66958093, -0.08674076,  0.20003531])

In [9]:
arr>0

array([False, False, False, False,  True,  True, False,  True, False,
        True])

In [10]:
(arr>0).sum()

4

#sum will give the total items where the condition is meet.
doesnt give sum of all positive numbers but only the count of numbers where condition is meet.

In [12]:
arr<0

array([ True,  True,  True,  True, False, False,  True, False,  True,
       False])

In [13]:
(arr<0).sum()

6

#any & all

In [14]:
arr2=np.array([True,False,True])

In [15]:
arr2

array([ True, False,  True])

In [16]:
arr2.any() # returns true if any items evaluates to true.

True

In [18]:
arr2.all() # returns true if all items evaluates to True.

False

#dot product of 2 matricies or arrays.

In [20]:
a=np.array([[1,2,3],[4,5,6]])

In [21]:
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
b=np.array([[6,7],[8,9],[10,11]])

In [23]:
print(b)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [24]:
a.dot(b)

array([[ 52,  58],
       [124, 139]])

#Inverse matrix

In [26]:
a1=np.random.randn(2,2)

In [27]:
print(a1)

[[ 0.80712407 -0.89570434]
 [ 0.247481   -0.46070254]]


In [29]:
from numpy.linalg import inv

In [30]:
inv(a1)

array([[ 3.06778537, -5.96443131],
       [ 1.64795832, -5.37458163]])

In [31]:
a2=np.random.randn(3,3)

In [32]:
print(a2)

[[ 2.11944786 -0.06569509 -0.66048163]
 [ 0.21319448 -0.83110224  0.56793923]
 [-1.65074647  1.19016351  1.01009837]]


In [33]:
inv(a2)

array([[ 0.63206453,  0.30018508,  0.24451097],
       [ 0.48084454, -0.43817348,  0.56078191],
       [ 0.46638494,  1.00685991,  0.72884332]])