In [1]:
import numpy as np

In [2]:
a=np.arange(10)

In [3]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
np.save("numpy 6a file saved array",a)

In [5]:
np.load("numpy 6a file saved array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# to save a single array.

In [7]:
b=np.arange(15)

In [8]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [9]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
#to save multiple arrays.

In [24]:
np.savez("numpy 6b file multi array save",ab=a,cd=b)

In [25]:
c=np.load("numpy 6b file multi array save.npz")

In [26]:
c['ab']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
c['cd']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
#compressed file

In [34]:
np.savez_compressed("numpy 6b file multi array save compressed",e=a,f=b)

In [35]:
d=np.load("numpy 6b file multi array save compressed.npz")

In [36]:
d['e']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
d['f']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#ravel flattern