In [1]:
import numpy as np

In [2]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

#Boolean Indexing

In [4]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
#will give its comparision operator gives the o/p as True or False.

In [6]:
data=np.random.randn(7,4)

In [7]:
data

array([[ 0.08189834,  0.29386787, -2.15837975, -0.22176162],
       [-0.6617236 , -0.39619167, -0.38301152,  1.06820431],
       [ 0.45839696,  0.30053034,  0.20138181, -0.93013001],
       [-0.36582155,  0.61300481, -0.37413591,  0.0440028 ],
       [ 0.01703571, -0.31370588, -0.34796748,  0.09065326],
       [ 0.88287159,  0.05888758, -1.22044513, -1.02595618],
       [ 1.35130391,  0.03252698, -0.12626201,  1.86138528]])

In [9]:
data[names=='Bob']

array([[ 0.08189834,  0.29386787, -2.15837975, -0.22176162],
       [-0.36582155,  0.61300481, -0.37413591,  0.0440028 ]])

In [10]:
#data of names=='Bob' gives only the rows where Bob is True. Here it is row 1 & row4

In [11]:
data[names=='Joe']

array([[-0.6617236 , -0.39619167, -0.38301152,  1.06820431],
       [ 0.88287159,  0.05888758, -1.22044513, -1.02595618],
       [ 1.35130391,  0.03252698, -0.12626201,  1.86138528]])

In [12]:
#data of names=='Joe' gives only the rows where Joe is True. Here it is row 2  row6 & row 7.

In [13]:
data[names=='Will']

array([[ 0.45839696,  0.30053034,  0.20138181, -0.93013001],
       [ 0.01703571, -0.31370588, -0.34796748,  0.09065326]])

In [14]:
#above is comparing 1d with nd arrays.

#Boolean Indexing using 2 n-d arrays.

In [26]:
#creating a new 7*4 array as data1

In [27]:
data1=np.arange(28).reshape(7,4)

In [28]:
data1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
#comparing data array with data1 array in which the items in data1 is divisible by 0

In [24]:
data[data1%7==0]

array([ 0.08189834,  1.06820431, -0.37413591,  0.05888758])

In [30]:
data[data1%7==0]=0 # reassign the items which satisfy the above statement in array to 0

In [31]:
data

array([[ 0.        ,  0.29386787, -2.15837975, -0.22176162],
       [-0.6617236 , -0.39619167, -0.38301152,  0.        ],
       [ 0.45839696,  0.30053034,  0.20138181, -0.93013001],
       [-0.36582155,  0.61300481,  0.        ,  0.0440028 ],
       [ 0.01703571, -0.31370588, -0.34796748,  0.09065326],
       [ 0.88287159,  0.        , -1.22044513, -1.02595618],
       [ 1.35130391,  0.03252698, -0.12626201,  1.86138528]])

In [32]:
#Array creation functions.

In [33]:
c=([1,2,3,0],4,5,6)

In [34]:
b=np.asarray(c)

In [35]:
print(b)

[list([1, 2, 3, 0]) 4 5 6]


In [36]:
b

array([list([1, 2, 3, 0]), 4, 5, 6], dtype=object)

In [37]:
d=([1,2,3,'0','hello'],4,5,6,'hi',{1:'sai'})

In [38]:
e=np.asarray(d)

In [39]:
print(e)

[list([1, 2, 3, '0', 'hello']) 4 5 6 'hi' {1: 'sai'}]
