In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

randn

In [10]:
data=np.random.randn(2,3)

In [11]:
data

array([[-0.34122625,  0.48920817,  0.41073175],
       [-1.96739378,  0.90730607,  0.35187561]])

#randn gives both +ve & -ve numbers.

In [13]:
data0=np.random.randn()

In [14]:
data0

-1.610065257664494

#randn without any arg gives an random float values

In [18]:
data1=np.random.rand(6)

In [19]:
data1

array([0.30177923, 0.08006574, 0.01436527, 0.40772059, 0.4844919 ,
       0.61155094])

#rand gives +ve numbers between 0 & 1

In [20]:
data

array([[-0.34122625,  0.48920817,  0.41073175],
       [-1.96739378,  0.90730607,  0.35187561]])

In [21]:
data1

array([0.30177923, 0.08006574, 0.01436527, 0.40772059, 0.4844919 ,
       0.61155094])

In [22]:
data.shape

(2, 3)

In [23]:
data1.shape

(6,)

In [24]:
data+data1 # Value error cant do arthimetic operators on 2 different shapes of arrays.

ValueError: operands could not be broadcast together with shapes (2,3) (6,) 

In [25]:
data2=np.random.rand(2,3)

In [26]:
data2

array([[0.07006693, 0.04072376, 0.31173436],
       [0.95955105, 0.35301274, 0.49505942]])

In [27]:
print(data2)

[[0.07006693 0.04072376 0.31173436]
 [0.95955105 0.35301274 0.49505942]]


In [28]:
print(data)

[[-0.34122625  0.48920817  0.41073175]
 [-1.96739378  0.90730607  0.35187561]]


#all arthimetic operators can work between 2 arrays (+,-,*,/,//,%,**) of same shape

In [35]:
print(data+data2)

[[-0.27115932  0.52993193  0.72246611]
 [-1.00784273  1.26031881  0.84693503]]


In [36]:
print(data-data2)

[[-0.41129318  0.44848441  0.09899739]
 [-2.92694483  0.55429332 -0.14318381]]


In [37]:
print(data/data2)

[[-4.87000422 12.01284497  1.31756971]
 [-2.05032737  2.57017935  0.71077449]]


In [38]:
print(data*data2)

[[-0.02390868  0.01992239  0.1280392 ]
 [-1.88781476  0.3202906   0.17419933]]


In [39]:
print(data//data2)

[[-5. 12.  1.]
 [-3.  2.  0.]]


In [40]:
print(data**data2)

[[       nan 0.97130364 0.75776202]
 [       nan 0.96624344 0.59626001]]


/Users/saisandeeptatineni/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


In [41]:
print(data)

[[-0.34122625  0.48920817  0.41073175]
 [-1.96739378  0.90730607  0.35187561]]


In [42]:
data3=np.random.randn(3,2)

In [43]:
data3

array([[ 1.0294867 , -0.29881512],
       [-0.71765818,  0.8282878 ],
       [ 0.29502254, -1.34504183]])

In [45]:
data+data3 # both arrays must be of same shape to do the airthemetic operations.

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [46]:
print(data)

[[-0.34122625  0.48920817  0.41073175]
 [-1.96739378  0.90730607  0.35187561]]


In [47]:
print(data2)

[[0.07006693 0.04072376 0.31173436]
 [0.95955105 0.35301274 0.49505942]]


#comparing 2 arrays the o/p is in the form of a boolean. Compares tehvalues of both individual values.

In [50]:
data>data2

array([[False,  True,  True],
       [False,  True, False]])

#slicing of 1-d arrays. Same as normal

In [57]:
a=np.arange(10)

In [58]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [59]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a[2]

2

In [62]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [63]:
#slicing a n dimentional array

In [66]:
a2=np.array([[1,2,3],[4,5,6]])

In [67]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a2[1:]

array([[4, 5, 6]])

In [70]:
a2[:,:1] # alll elements in ros but only until 1 in columns.

array([[1],
       [4]])

In [71]:
a2[1,1]

5

In [72]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [73]:
a2[:,:-1]

array([[1, 2],
       [4, 5]])

#rearranging values for existing values.

In [77]:
a2[:,:-1]=[[10,20],[40,50]]

In [78]:
a2

array([[10, 20,  3],
       [40, 50,  6]])